services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt && python Project/manage.py collectstatic --noinput && python Project/manage.py migrate
    startCommand: sh -c 'cd Project && gunicorn Project.wsgi:application'
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: django-project-q0rp.onrender.com,localhost,127.0.0.1
      - key: SECRET_KEY
        value: your-secret-key-here
